#!/bin/sh

set -ex

. ../inc/lib.sh

curl_version=7.26.0

fetch_curl
prep_build_and_cd

sudo apt-get install `gnutls_deps`

tar xfz ../curl-$curl_version.tar.gz
cd curl-$curl_version
./configure --prefix=$DEST_HOME/opt/curl-$curl_version-gnutls-gssapi \
  --without-ssl --without-nss --with-gssapi \
  --with-gnutls
make
# building in vagrant, installing to $DEST_HOME
sudo make install

cd ../..
tar cfJ curl-$curl_version-gnutls-gssapi-precise-64.tar.xz -C $DEST_HOME/opt curl-$curl_version-gnutls-gssapi
