#!/bin/sh

set -ex

. ../inc/lib.sh

curl_version=7.26.0

rm -rf build
mkdir build
cd build
(cd .. && wget_once http://curl.haxx.se/download/curl-$curl_version.tar.gz)

sudo apt-get install `gnutls_deps`

tar xfz ../curl-$curl_version.tar.gz
cd curl-$curl_version
./configure --prefix=$DEST_HOME/opt/curl-$curl_version-gnutls-gssapi \
  --without-ssl --without-nss --with-gssapi \
  --with-gnutls
make
# building in vagrant, installing to $DEST_HOME
sudo make install

cd ../..
tar cfz curl-$curl_version-gnutls-gssapi-precise-64.tar.gz -C $DEST_HOME/opt curl-$curl_version-gnutls-gssapi
