#!/bin/sh

set -ex

. ../inc/lib.sh

curl_version=7.68.0
openssl11_version=1.1.1d
openssl10_version=1.0.2u
libressl_version=3.0.2
nghttp2_version=1.40.0

fetch_curl
fetch_nghttp2

prep_build_and_cd

sudo apt-get install `all_deps` pkg-config

build_nghttp2
setup_nghttp2_envvars

build_curl_7_43_0_or_higher openssl11-gssapi-libssh2 "--without-gnutls --without-nss --with-gssapi --with-libssh2 --with-ssl=/home/travis/opt/openssl-$openssl11_version --with-nghttp2=/home/travis/opt/nghttp2-$nghttp2_version"
build_curl_7_43_0_or_higher openssl10-gssapi-libssh2 "--without-gnutls --without-nss --with-gssapi --with-libssh2 --with-ssl=/home/travis/opt/openssl-$openssl10_version --with-nghttp2=/home/travis/opt/nghttp2-$nghttp2_version"
build_curl_7_43_0_or_higher gnutls-gssapi-libssh2 "--without-ssl --without-nss --with-gnutls --with-gssapi --with-libssh2"
build_curl_7_43_0_or_higher nss-gssapi-libssh2 "--without-ssl --without-gnutls --with-nss --with-gssapi --with-libssh2"
build_curl_7_43_0_or_higher none "--without-ssl --without-gnutls --without-nss --without-gssapi"
build_curl_7_43_0_or_higher libressl-gssapi-libssh2 "--without-gnutls --without-nss --with-ssl=$DEST_HOME/opt/libressl-$libressl_version --with-gssapi --with-libssh2"

ldd $DEST_HOME/opt/curl-$curl_version-openssl11-gssapi-libssh2/lib/libcurl.so |grep libssl
ldd $DEST_HOME/opt/curl-$curl_version-openssl10-gssapi-libssh2/lib/libcurl.so |grep libssl
#ldd $DEST_HOME/opt/curl-$curl_version-gnutls-gssapi-libssh2/lib/libcurl.so |grep libgnutls
ldd $DEST_HOME/opt/curl-$curl_version-nss-gssapi-libssh2/lib/libcurl.so |grep libnss
! ldd $DEST_HOME/opt/curl-$curl_version-none/lib/libcurl.so |egrep 'lib(ssl|gnutls|nss)'
ldd $DEST_HOME/opt/curl-$curl_version-libressl-gssapi-libssh2/lib/libcurl.so |grep libssl
