#!/bin/sh

set -ex

. ../inc/lib.sh

curl_version=7.19.0

fetch_old_curl
prep_build_and_cd

sudo apt-get install libkrb5-dev

tar xfz ../curl-$curl_version.tar.gz
cd curl-$curl_version
patch -p1 <../../curl-7.19.0/debian/patches/curl-7.19.0-sslv2-c66b0b32fba-modified.patch
./configure --prefix=$DEST_HOME/opt/curl-$curl_version-openssl-gssapi \
  --without-gnults --without-nss --with-gssapi \
  --with-ssl
make
# building in vagrant, installing to $DEST_HOME
sudo make install

cd ../..
tar cfJ curl-$curl_version-openssl-gssapi-$DISTRO-64.tar.xz \
  -C $DEST_HOME/opt curl-$curl_version-openssl-gssapi
