#!/bin/sh

set -ex

. ../inc/lib.sh

curl_version=7.19.0

rm -rf build
mkdir build
cd build
(cd .. && wget_once http://curl.haxx.se/download/archeology/curl-$curl_version.tar.gz)

sudo apt-get install libkrb5-dev

tar xfz ../curl-$curl_version.tar.gz
cd curl-$curl_version
patch -p1 <../../curl-7.19.0/debian/patches/curl-7.19.0-sslv2-c66b0b32fba-modified.patch
./configure --prefix=$DEST_HOME/opt/curl-$curl_version-openssl-gssapi \
  --without-gnults --without-nss --with-gssapi \
  --with-ssl
make
# building in vagrant, installing to $DEST_HOME
sudo make install

cd ../..
tar cfz curl-$curl_version-openssl-gssapi-precise-64.tar.gz \
  -C $DEST_HOME/opt curl-$curl_version-openssl-gssapi
