#!/bin/sh

set -ex

. ../inc/lib.sh

curl_version=7.38.0
nghttp2_version=0.6.2

fetch_curl
fetch_nghttp2

prep_build_and_cd

sudo apt-get install `gnutls_deps`

build_nghttp2
setup_nghttp2_envvars

tar xfz ../curl-$curl_version.tar.gz
cd curl-$curl_version
./configure --prefix=$DEST_HOME/opt/curl-$curl_version-gnutls-gssapi \
  --with-nghttp2=$DEST_HOME/opt/nghttp2-$nghttp2_version \
  --without-ssl --without-nss --with-gssapi \
  --with-gnutls
make
# building in vagrant, installing to $DEST_HOME
sudo make install

cd ..

pack_curl gnutls-gssapi
