#!/bin/sh

set -ex

. ../inc/lib.sh

curl_version=7.44.0
libressl_version=2.2.0

prep_build_and_cd
fetch_curl

sudo apt-get install `all_deps`

setup_nghttp2_envvars

build_curl_7_43_0_or_higher \
  gnutls-gssapi-libssh2 "--without-ssl --without-nss --with-gnutls --with-gssapi --with-libssh2"

ldd $DEST_HOME/opt/curl-$curl_version-gnutls-gssapi/lib/libcurl.so |grep libgnutls
