#!/bin/sh

set -ex

. ../inc/lib.sh

curl_version=7.46.0
libressl_version=2.2.0

prep_build_and_cd
fetch_curl

sudo apt-get install `all_deps`

setup_nghttp2_envvars

build_curl_7_43_0_or_higher openssl-gssapi-libssh2 "--without-gnutls --without-nss --with-ssl --with-gssapi --with-libssh2"
#build_curl_7_43_0_or_higher gnutls-gssapi-libssh2 "--without-ssl --without-nss --with-gnutls --with-gssapi --with-libssh2"
build_curl_7_43_0_or_higher nss-gssapi-libssh2 "--without-ssl --without-gnutls --with-nss --with-gssapi --with-libssh2"
build_curl_7_43_0_or_higher none "--without-ssl --without-gnutls --without-nss --without-gssapi"
build_curl_7_43_0_or_higher libressl-gssapi-libssh2 "--without-gnutls --without-nss --with-ssl=$DEST_HOME/opt/libressl-$libressl_version --with-gssapi --with-libssh2"

ldd $DEST_HOME/opt/curl-$curl_version-openssl-gssapi-libssh2/lib/libcurl.so |grep libssl
#ldd $DEST_HOME/opt/curl-$curl_version-gnutls-gssapi-libssh2/lib/libcurl.so |grep libgnutls
ldd $DEST_HOME/opt/curl-$curl_version-nss-gssapi-libssh2/lib/libcurl.so |grep libnss
! ldd $DEST_HOME/opt/curl-$curl_version-none/lib/libcurl.so |egrep 'lib(ssl|gnutls|nss)'
ldd $DEST_HOME/opt/curl-$curl_version-libressl-gssapi-libssh2/lib/libcurl.so |grep libssl
