#!/bin/sh

set -ex

. ../inc/lib.sh

libressl_version=2.7.3

prep_build_and_cd

(cd .. && wget_once http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$libressl_version.tar.gz)

tar xfz ../libressl-$libressl_version.tar.gz
cd libressl-$libressl_version
./configure --prefix=$DEST_HOME/opt/libressl-$libressl_version
make
sudo make install

cd ../..
tar cfJ libressl-$libressl_version-$DISTRO-64.tar.xz -C $DEST_HOME/opt libressl-$libressl_version
