#!/bin/sh

set -ex

wget_once() {
  url="$1"
  if ! test -f `basename "$url"`; then
    wget -O `basename "$url"`.part "$url"
    rv=$?
    if test $rv = 0; then
      mv `basename "$url"`.part `basename "$url"`
    else
      rm -f `basename "$url"`.part
      return $rv
    fi
  fi
}

wget_once_to() {
  url="$1"
  dest="$2"
  if ! test -f "$dest"; then
    wget -O "$dest".part "$url"
    rv=$?
    if test $rv = 0; then
      mv "$dest".part "$dest"
    else
      rm -f "$dest".part
      return $rv
    fi
  fi
}

libressl_version=2.2.0
curl_version=7.19.7
DEST_HOME=/home/travis

rm -rf build
mkdir build
cd build

(cd .. && wget_once http://ftp.openbsd.org/pub/OpenBSD/LibreSSL/libressl-$libressl_version.tar.gz)

tar xfz ../libressl-$libressl_version.tar.gz
cd libressl-$libressl_version
./configure --prefix=$DEST_HOME/opt/libressl-$libressl_version
make
sudo make install

cd ../..
tar cfz libressl-$libressl_version-precise-64.tar.gz -C $DEST_HOME/opt libressl-$libressl_version
