#!/bin/sh

set -ex

wget_once() {
  url="$1"
  if ! test -f `basename "$url"`; then
    wget -O `basename "$url"`.part "$url"
    rv=$?
    if test $rv = 0; then
      mv `basename "$url"`.part `basename "$url"`
    else
      rm -f `basename "$url"`.part
      return $rv
    fi
  fi
}

wget_once_to() {
  url="$1"
  dest="$2"
  if ! test -f "$dest"; then
    wget -O "$dest".part "$url"
    rv=$?
    if test $rv = 0; then
      mv "$dest".part "$dest"
    else
      rm -f "$dest".part
      return $rv
    fi
  fi
}

python_version=3.1.5
DEST_HOME=/home/travis

rm -rf build
mkdir build
cd build

(cd .. && wget_once https://www.python.org/ftp/python/$python_version/Python-$python_version.tgz)

tar xfz ../Python-$python_version.tgz
cd Python-$python_version
./configure --prefix=$DEST_HOME/opt/python-3.1
make
sudo make install

cd ../..
tar cfz python-3.1-precise-64.tar.gz -C $DEST_HOME/opt python-3.1
