#!/bin/sh

set -ex

. ../inc/lib.sh

python_version=3.1.5

prep_build_and_cd

(cd .. && wget_once https://www.python.org/ftp/python/$python_version/Python-$python_version.tgz)

tar xfz ../Python-$python_version.tgz
cd Python-$python_version
./configure --prefix=$DEST_HOME/opt/python-3.1
make
sudo make install

cd ../..
tar cfJ python-3.1-precise-64.tar.xz -C $DEST_HOME/opt python-3.1
