#!/bin/sh

set -ex

. ../inc/lib.sh

python_version=3.1.5
DEST_HOME=/home/travis

rm -rf build
mkdir build
cd build

(cd .. && wget_once https://www.python.org/ftp/python/$python_version/Python-$python_version.tgz)

tar xfz ../Python-$python_version.tgz
cd Python-$python_version
./configure --prefix=$DEST_HOME/opt/python-3.1
make
sudo make install

cd ../..
tar cfz python-3.1-precise-64.tar.gz -C $DEST_HOME/opt python-3.1
